name: Packaging

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build twine
    - name: Build package
      run: |
        pyproject-build .
        twine check --strict dist/*
    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
  publish:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04
    needs: build
    environment:
      name: pypi
      url: https://pypi.org/project/win32-setctime/
    permissions:
      id-token: write
    steps:
    - name: Download package
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
